name: guandan_server
description: Guan Dan WebSocket game server
version: 0.1.1
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  guandan_shared:
    path: ../shared

dev_dependencies:
  test: ^1.25.0
